# Generated by Django 3.0.7 on 2020-06-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enable', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enable', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('enable', models.BooleanField(default=True, verbose_name='有効')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(verbose_name='締め切り')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='講義科目')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Professor', verbose_name='担当教員'),
        ),
    ]
