# Generated by Django 3.0.7 on 2020-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='period',
            field=models.IntegerField(choices=[(0, '前期'), (1, '後期')], default=0, verbose_name='学期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='年度'),
            preserve_default=False,
        ),
    ]
